name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-interaction --no-ansi

    - name: Run black
      run: poetry run black --check .

    - name: Run flake8
      run: poetry run flake8 src tests

    - name: Run mypy
      run: poetry run mypy src

    - name: Run pytest
      run: poetry run pytest --maxfail=1 --disable-warnings -q
